version: "3.7"
services:
  flask_server:
    container_name: flask_server
    restart: always
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=./flask_server/app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/flask_server
    networks:
      ml-network:
        aliases:
          - flask_server

networks:
  ml-network: